package(default_visibility = ["//im2latex:internal"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "image_processing",
    srcs = ["image_processing.py"],
    srcs_version = "PY2AND3",
)

py_library(
    name = "image_embeddings",
    srcs = ["image_embeddings.py"],
    srcs_version = "PY2AND3",
)

py_library(
    name = "inputs",
    srcs = ["inputs.py"],
    srcs_version = "PY2AND3",
)
